site_name: The Internals of PySpark
site_url: https://books.japila.pl/pyspark-internals/
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of PySpark

repo_name: pyspark-internals
repo_url: https://github.com/japila-books/pyspark-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2021 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - search.share
    - search.highlight
    - navigation.indexes
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date:
      enabled_if_env: CI
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
  spark:
    version: 3.1.1
    github: https://github.com/apache/spark/tree/v3.1.1
    doc: http://spark.apache.org/docs/3.1.1
  book:
    spark_core: https://books.japila.pl/apache-spark-internals
    spark_sql: https://jaceklaskowski.github.io/mastering-spark-sql-book
  python:
    version: 3.6
    doc: https://docs.python.org/3
  py4j:
    version: 0.10.9
    doc: https://www.py4j.org
    javadoc: https://www.py4j.org/_static/javadoc

nav:
  - Home: index.md
  - Internals:
    - Overview: overview.md
    - Setup: Setup.md
    - Building from Sources: building-from-sources.md
    - Configuration Properties: configuration-properties.md
    - Environment Variables: environment-variables.md
    - spark-submit: spark-submit.md
    - PySpark Shell: pyspark.md
    - PythonRunner: PythonRunner.md
    - PythonGatewayServer: PythonGatewayServer.md
    - Py4JServer: Py4JServer.md
    - shell.py: shell.md
    - SparkConf: SparkConf.md
    - SparkContext: SparkContext.md
    - PythonWorkerFactory: PythonWorkerFactory.md
    - MonitorThread: MonitorThread.md
    - PythonFunction: PythonFunction.md
    - PythonRDD: PythonRDD.md
    - PythonForeachWriter: PythonForeachWriter.md
    - PythonAccumulatorV2: PythonAccumulatorV2.md
    - PythonBroadcast: PythonBroadcast.md
    - SocketAuthServer: SocketAuthServer.md
    - SocketFuncServer: SocketFuncServer.md
    - SocketAuthHelper: SocketAuthHelper.md
    - Mixins:
      - SparkConversionMixin: SparkConversionMixin.md
    - Logging: spark-logging.md
  - Packages:
    - pyspark:
      - java_gateway.py: pyspark/java_gateway.md
    - pyspark.sql:
      - udf.py: pyspark/sql/udf.md
      - functions.py: pyspark/sql/functions.md
    - pyspark.sql.pandas:
      - functions.py: pyspark/sql/pandas/functions.md
  - PySpark SQL:
    - sql/index.md
    - SQLContext: sql/SQLContext.md
    - SparkSession: sql/SparkSession.md
    - DataFrame: sql/DataFrame.md
    - PandasMapOpsMixin: sql/PandasMapOpsMixin.md
    - PandasConversionMixin: sql/PandasConversionMixin.md
    - PythonUDF: sql/PythonUDF.md
    - UserDefinedFunction: sql/UserDefinedFunction.md
    - UserDefinedPythonFunction: sql/UserDefinedPythonFunction.md
    - GroupedData: sql/GroupedData.md
    - PandasGroupedOpsMixin: sql/PandasGroupedOpsMixin.md
    - PandasCogroupedOps: sql/PandasCogroupedOps.md
    - RelationalGroupedDataset: sql/RelationalGroupedDataset.md
    - UDFRegistration: sql/UDFRegistration.md
    - Logical Operators:
      - FlatMapGroupsInPandas: sql/FlatMapGroupsInPandas.md
    - Physical Operators:
      - AggregateInPandasExec: sql/AggregateInPandasExec.md
      - FlatMapGroupsInPandasExec: sql/FlatMapGroupsInPandasExec.md
  - Python Runners:
    - BasePythonRunner: runners/BasePythonRunner.md
    - PythonRunner: runners/PythonRunner.md
    - ArrowPythonRunner: runners/ArrowPythonRunner.md
    - PythonUDFRunner: runners/PythonUDFRunner.md
