site_name: The Internals of PySpark
site_url: https://books.japila.pl/pyspark-internals/
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of PySpark

repo_name: pyspark-internals
repo_url: https://github.com/japila-books/pyspark-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    # https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-path
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros
  # https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin
  - meta
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # - tags:
  #     enabled: !ENV [CI, false]
  #     tags_extra_files:
  #       developer-api.md:
  #         - DeveloperApi
  # https://github.com/squidfunk/mkdocs-material/issues/5241
  # # https://squidfunk.github.io/mkdocs-material/reference/#built-in-typeset-plugin
  - typeset

extra:
  arrow:
    docs: https://arrow.apache.org/docs
    home: https://arrow.apache.org/
  book:
    title: PySpark
    spark_core: https://books.japila.pl/apache-spark-internals
    spark_sql: https://books.japila.pl/spark-sql-internals
    spark_k8s: https://jaceklaskowski.github.io/spark-kubernetes-book
  pandas:
    version: 1.5.0
    api: https://pandas.pydata.org/docs/reference/api
    home: https://pandas.pydata.org/
  py4j:
    version: 0.10.9
    doc: https://www.py4j.org
    javadoc: https://www.py4j.org/_static/javadoc
  python:
    version: 3.11
    docs: https://docs.python.org/3
    api: https://docs.python.org/3
    peps: https://peps.python.org
  pytorch:
    docs: https://pytorch.org/docs/stable
    github: https://github.com/pytorch/pytorch
    tutorials: https://pytorch.org/tutorials
  scala:
    api: https://www.scala-lang.org/api/2.13.8
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@jaceklaskowski
  spark:
    version: 3.4.0
    github: https://github.com/apache/spark/tree/v3.4.0
    jira: https://issues.apache.org/jira/browse
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#tag-icons-and-identifiers
  tags:
    DeveloperApi: developerapi

nav:
  - index.md
  - Features:
    - features/index.md
    - ... | arrow-optimization/**.md
    - ... | pytorch-distributed/**.md
    - ... | pandas-on-spark/**.md
    - ... | pandas-udfs/**.md
    - ... | connect/**.md
    - PySpark Shell: pyspark.md
  - ... | ml/**.md
  - ... | sql/**.md
  - Internals:
    - Overview: overview.md
    - Setup: Setup.md
    - Building from Sources: building-from-sources.md
    - Configuration Properties: configuration-properties.md
    - Environment Variables: environment-variables.md
    - PythonRunner: PythonRunner.md
    - PythonGatewayServer: PythonGatewayServer.md
    - Py4JServer: Py4JServer.md
    - SparkConf: SparkConf.md
    - SparkContext: SparkContext.md
    - PythonWorkerFactory: PythonWorkerFactory.md
    - MonitorThread: MonitorThread.md
    - PythonFunction: PythonFunction.md
    - PythonRDD: PythonRDD.md
    - PythonForeachWriter: PythonForeachWriter.md
    - PythonAccumulatorV2: PythonAccumulatorV2.md
    - PythonBroadcast: PythonBroadcast.md
    - SimplePythonFunction: SimplePythonFunction.md
    - SocketAuthServer: SocketAuthServer.md
    - SocketFuncServer: SocketFuncServer.md
    - SocketAuthHelper: SocketAuthHelper.md
    - logging.md
  - Packages:
    - pyspark:
      - java_gateway.py: pyspark/java_gateway.md
      - shell.py: pyspark/shell.md
    - pyspark.pandas:
      - pyspark/pandas/index.md
      - pyspark/pandas/DataFrame.md
      - pyspark/pandas/InternalFrame.md
    - pyspark.pandas.generic:
      - pyspark/pandas/generic/index.md
      - pyspark/pandas/generic/Frame.md
    - pyspark.sql:
      - udf.py: pyspark/sql/udf.md
      - functions.py: pyspark/sql/functions.md
    - pyspark.sql.pandas:
      - pyspark/sql/pandas/index.md
      - functions.py: pyspark/sql/pandas/functions.md
      - pyspark/sql/pandas/PandasUDFType.md
  - ... | runners/**.md
  - ... | demo/**.md
