site_name: The Internals of PySpark
site_url: https://books.japila.pl/pyspark-internals/
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of PySpark

repo_name: pyspark-internals
repo_url: https://github.com/japila-books/pyspark-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2021 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - search.share
    - search.highlight
    - navigation.indexes
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date:
      enabled_if_env: CI
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
  spark:
    version: 3.1.1-rc3
    github: https://github.com/apache/spark/tree/v3.1.1-rc3
    doc: http://spark.apache.org/docs/3.0.1
  book:
    spark_core: https://books.japila.pl/apache-spark-internals
    spark_sql: https://jaceklaskowski.github.io/mastering-spark-sql-book
  python:
    version: 3.6
    doc: https://docs.python.org/3
  py4j:
    version: 0.10.9
    doc: https://www.py4j.org

nav:
  - Home: index.md
  - Internals:
    - Overview: overview.md
    - Setup: Setup.md
    - Building from Sources: building-from-sources.md
    - Configuration Properties: configuration-properties.md
    - PythonWorkerFactory: PythonWorkerFactory.md
    - PythonGatewayServer: PythonGatewayServer.md
    - Py4JServer: Py4JServer.md
    - java_gateway.py: java_gateway.md
    - shell.py: shell.md
    - functions.py: functions.md
    - SparkContext: SparkContext.md
    - SparkSession: SparkSession.md
    - MonitorThread: MonitorThread.md
    - PythonUDF: PythonUDF.md
    - UserDefinedPythonFunction: UserDefinedPythonFunction.md
    - PythonFunction: PythonFunction.md
    - PythonRDD: PythonRDD.md
    - PythonForeachWriter: PythonForeachWriter.md
    - PythonAccumulatorV2: PythonAccumulatorV2.md
    - PythonBroadcast: PythonBroadcast.md
    - SocketAuthServer: SocketAuthServer.md
    - SocketFuncServer: SocketFuncServer.md
    - SocketAuthHelper: SocketAuthHelper.md
    - SQLContext: SQLContext.md
    - DataFrame: DataFrame.md
    - GroupedData: GroupedData.md
    - RelationalGroupedDataset: RelationalGroupedDataset.md
    - UDFRegistration: UDFRegistration.md
    - UserDefinedFunction: UserDefinedFunction.md
    - Mixins:
      - PandasCogroupedOps: PandasCogroupedOps.md
      - PandasConversionMixin: PandasConversionMixin.md
      - PandasGroupedOpsMixin: PandasGroupedOpsMixin.md
      - PandasMapOpsMixin: PandasMapOpsMixin.md
      - SparkConversionMixin: SparkConversionMixin.md
    - Logging: spark-logging.md
  - Logical Operators:
    - FlatMapGroupsInPandas: logical-operators/FlatMapGroupsInPandas.md
  - Physical Operators:
    - AggregateInPandasExec: physical-operators/AggregateInPandasExec.md
    - FlatMapGroupsInPandasExec: physical-operators/FlatMapGroupsInPandasExec.md
  - Python Runners:
    - BasePythonRunner: BasePythonRunner.md
    - PythonRunner: PythonRunner.md
    - ArrowPythonRunner: ArrowPythonRunner.md
    - PythonUDFRunner: PythonUDFRunner.md
  - Packages:
    - pyspark.sql:
      - udf.py: pyspark/sql/udf.md
      - functions.py: pyspark/sql/functions.md
  - DataFrame:
    - toPandas: dataframe/toPandas.md
